language: node_js
node_js:
- "0.10"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "sleep 5"

  # Workaround for Selenium #3280 issue
- "sudo sed -i 's/^127\\.0\\.0\\.1.*$/127.0.0.1 localhost/' /etc/hosts"

script: npm run test

env:
  global:
    - secure: lSlkRu9CXE5+ZdlPKa18EEK9Uz6JoS//E5VblRm4dqPiVQKMvIBY8/j5qJIoIWMfZ+YIkd7VUrHPDUC6OWGvpCZ8uQtB8IyWytoB22CAP2pu/3cP3fwFU/jKaejTMkorH8kvMMjRFx7OaKUu9ODvtSgAxCUW2JhVpxpOpaIxBm0=
    - secure: SGYYo3CDBFJWtmEDTQ8Llo+ReRo/hFHskt5ghKTmpbZsTwLWgEepGLZbg+ABwbCpn4V0vkFMC8FJ/9x6uqsFgNOlGet5M/cUFcgUCTUnqT1jKe4a2QOdXT9udFyYrmgydAWbuMaN2kAXKWgOjWLcVF5Aa0+mO8iQpV4oet5+oq4=

  matrix:
  - CLIENT=saucelabs:firefox:34 # pinning version, see https://code.google.com/p/selenium/issues/detail?id=8390
  - CLIENT=saucelabs:chrome
  - CLIENT=saucelabs:safari:6
  - CLIENT="saucelabs:iphone:8.1:OS X 10.9"
  - CLIENT="saucelabs:internet explorer:11:Windows 8.1"
  # FIXME:
  # - CLIENT="saucelabs:internet explorer:10:Windows 8"
